# Generated by Django 5.0.6 on 2024-06-07 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uquv_yil', models.CharField(max_length=25, verbose_name="o'quv yili")),
                ('smester', models.CharField(choices=[('1', '1-semestr'), ('2', '2-semestr'), ('3', '3-semestr'), ('4', '4-semestr'), ('5', '5-semestr'), ('6', '6-semestr'), ('7', '7-semestr'), ('8', '8-semestr'), ('9', '9-semestr'), ('10', '10-semestr')], max_length=8, verbose_name='Semestr')),
                ('yunalish', models.CharField(choices=[('M_VA_I_Y', 'Matematika va informatika'), ('F_VA_A_Y', 'Fizika va astronomiya'), ('BOSH_TALIM_Y', "Boshlang'ich ta'lim"), ('TARIX_Y', 'Tarix '), ('BIOLOGIYA', 'Biologiya'), ('GEOGRAFIYA_VA_IQTISODIY_B_y', 'Geografiya va iqtisodiy bilim asoslari'), ('KIMYO', 'Kimyo'), ('MUSIQA_TA_Y', "Musiqa ta'limi"), ('TASVIR_S_Y', "Tasviriy san'at muxandislik grafikasi"), ('TEXNOLOGIK_T_F_K', "Texnologik ta'lim Fakultet kvalifikatsiyasi"), ('JISMONIY_MAD', 'Jismoniy madaniyat'), ('SPORT_FAOLIYATI', 'Sport faoliyati'), ('MAKTABGACHA_TALIM', "Maktabgacha ta'lim"), ('UZBEK_T_ADABIYOT', "O'zbek tili va adabiyoti"), ('UZGA_TILLI_GRUHLARGA_RUS_T', "O'zbek tilli guruhlarga rus tili"), ('XORIJIY_TIL_ADABIYOTI_ING', 'Xorijiy til va adabiyoti: ingliz tili')], max_length=80, verbose_name="Yo'nalish")),
                ('fakulteti', models.CharField(choices=[('AMALIY_M_F', 'Amaliy matematika va fizika'), ('2', "Boshlang'ich ta'lim va gumaniter fanlar funkuteti"), ('3', 'Tabiy fanlar fakulteri'), ('SANATSHUNOSLIK_FAKULTETE', "Sanatshunoslik fakul'teti"), ('JISMONIY_MADANIYAT_SPORT_VA_MK_TALIM', "Jismoniy madaniyat, sport va Maktabgacha ta'lim fakulteti"), ('FILOLOGIYA_FAKULTETI', 'filologiya fakulteti')], max_length=60, verbose_name='Fakulteti')),
                ('kafedra', models.CharField(choices=[('TEXNOLOGIYA_T_Y', 'TEXNOLOGIYA talim kafidrasi'), ('RUS_TILI_ADABIYOT_K', 'Rus tili va adabiyoti kafedrasi'), ('MATEMATIKA_VA_INFORMATIKA', 'Matematika va Informatika'), ('MAKTABGACHA_TALIM_K', " Maktabgacha ta'lim kafidrasi"), ('UZBEK_TILI_VA_ADABIYOTI_K', "o'zbek tili va adabiyoti kafedrasi"), ('BOSHLANGICH_TALIM_K', "Boshlang'ich talim nazariyasi kafedrasi"), ('PEDAGOGIKA_K', 'Pedagogika kafedrasi'), ('BOSHLANGICH_TALIM_METODIKASI_K', "Boshlang'ich talim metodikasi kafedrasi"), ('PSIXOLOGIYA_K', 'Psixologiya kafedrasi'), ('XORIJIY_TILLAR_K', 'Xorijiy tillar kafedrasi'), ('TASVIRIY_SANAT_VAmUHANDISLIK_K', "Tasviriy san'at va muhandislik grafikasi kafidrasi"), ('MUSIQA_TALIM_K', "Musiqa ta'lim kafedrasi"), ('SPORT_TURLARINI_UQITISH_METO_K', "Sport turlarini o'qitish metodikasi kafedrasi"), ('KIMYO_K', 'Kimyo kafedrasi'), ('FIZIKA_ASTRONOMIYA_K', 'Fizika astronomiya kafedrasi'), ('JISMONIY_MADANIYAT_NAZARIYASI_VA_MATEMATIKASI_K', 'Jismoniy madaniyat nazariyasi va m,k'), ('BIOLOGIYA_VA_GEOGRAFIYA_K', 'Biologiya va Geografiya kafedrasi'), ('IJTIMOIY_GUMANITAR_FANLAR_K', 'Ijtimoiy gumanitar fanlar Kafedrasi')], max_length=60, verbose_name='Kafedra')),
                ('gruh_nomi', models.CharField(max_length=200, verbose_name='Guruh nomi')),
                ('talaba_soni', models.IntegerField(verbose_name='Talaba soni')),
            ],
        ),
        migrations.CreateModel(
            name='Bahosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=200, verbose_name='fan nomi')),
                ('uquv_boshqarma_boshligi', models.CharField(help_text='F.I.SH', max_length=200, verbose_name="O'quv boshqarma boshlig'i")),
                ('oraliq_nazorat_masul', models.CharField(help_text='F.I.SH', max_length=150, verbose_name='Oraliq Nazorat Masuli')),
                ('boshqarma_boshligi', models.CharField(help_text='F.I.SH', max_length=150, verbose_name="O'qov-uslubiy boshqarma boshlig'i")),
                ('kafedra_mudiri', models.CharField(max_length=50, verbose_name='Kafedra mudiri')),
                ('fan_soat', models.IntegerField()),
                ('fan_kredit', models.CharField(blank=True, max_length=25, verbose_name='Fan krediti')),
                ('grops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.grops')),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250, verbose_name='Ismi')),
                ('familya', models.CharField(max_length=250, verbose_name='Familyasi')),
                ('ota', models.CharField(max_length=250, verbose_name='Otasining ismi')),
                ('talaba_id', models.IntegerField(verbose_name='Talaba ID')),
                ('gruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.grops', verbose_name='Gruh')),
            ],
        ),
        migrations.CreateModel(
            name='Talababaholash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField()),
                ('bahosi', models.IntegerField(blank=True)),
                ('fanlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.bahosi')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.talaba', verbose_name='Talabalar')),
            ],
        ),
    ]
